// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB09WMkqSAXswsM6V9mvVs79H8ssh9fmuE',
    appId: '1:735822693333:web:a3bf0a7ce5375d4997735c',
    messagingSenderId: '735822693333',
    projectId: 'smartkids-f4c34',
    authDomain: 'smartkids-f4c34.firebaseapp.com',
    storageBucket: 'smartkids-f4c34.appspot.com',
    measurementId: 'G-HJYNX554CJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPHF4vBR5VNT3eV6inhcC9kavBQ-Pynn8',
    appId: '1:735822693333:android:e9c71d77ac0eb0a797735c',
    messagingSenderId: '735822693333',
    projectId: 'smartkids-f4c34',
    storageBucket: 'smartkids-f4c34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzaLlrsvWHtN4n_FWdVPfZNSaBm3nvatE',
    appId: '1:735822693333:ios:063317982e7764df97735c',
    messagingSenderId: '735822693333',
    projectId: 'smartkids-f4c34',
    storageBucket: 'smartkids-f4c34.appspot.com',
    iosBundleId: 'com.example.smartKidsV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzaLlrsvWHtN4n_FWdVPfZNSaBm3nvatE',
    appId: '1:735822693333:ios:063317982e7764df97735c',
    messagingSenderId: '735822693333',
    projectId: 'smartkids-f4c34',
    storageBucket: 'smartkids-f4c34.appspot.com',
    iosBundleId: 'com.example.smartKidsV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB09WMkqSAXswsM6V9mvVs79H8ssh9fmuE',
    appId: '1:735822693333:web:88188b27b5eeabdb97735c',
    messagingSenderId: '735822693333',
    projectId: 'smartkids-f4c34',
    authDomain: 'smartkids-f4c34.firebaseapp.com',
    storageBucket: 'smartkids-f4c34.appspot.com',
    measurementId: 'G-85Z3EWJ6WP',
  );
}
